### PR TITLE
meta Tags Updated

### PR DESCRIPTION
**Pull request by lalitc375**
Meta Tags Updated

### CODE REVIEW

**Comment by CuriousLearner** [comment]
Hi @lalitc375 I just did some changes in latest commit of removing those links, can you update that please.

**Comment by lalitc375** [comment]
@CuriousLearner  Sure

**Comment by lalitc375** [comment]
@CuriousLearner  My branch is ahead of 'origin/gh-pages' by 1 commit.

**Comment by CuriousLearner** [comment]
Your PR is from branch 'lalitEdit' and you haven't pull the latest commit, that's why the links are being again over-written.

**Pull request closed without merging**
