### PR TITLE
Adding volunteers page

### PR DESCRIPTION
**Pull request by CuriousLearner**
Added volunteers page
Added link to it in the footer of index

### CODE REVIEW

**Comment by CuriousLearner** [comment]
@akshayaurora here it is. Please have a look.

**Comment by Warlord77** [comment]
Please add Sahil Joseph , Piyush Aggarwal

**Comment by akshayaurora** [comment]
@CuriousLearner @SahilJoseph is correct, plus add G.T.Rao

:+1:  for the pr

**Comment by CuriousLearner** [comment]
@SahilJoseph I guess it's "Peeyush Aggarwal" not "Piyush Aggarwal"

@akshayaurora Adding.

**Pull request merged**
